---
- name: Update and upgrade all packages
  apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 3600

- name: Install common dependencies
  apt:
    name:
      - curl
      - vim
      - wget
    state: present
