apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: react-frontend
        image: ayuleshava/frontend-app:latest   # Replace with your image
        env:
        - name: REACT_APP_API_BASE_URL
          value: "http://fastapi-service:8000"   # Make sure this points to the backend service in K8s
        ports:
        - containerPort: 80
