# apiVersion: v1
# kind: Service
# metadata:
#   name: react-service
#   namespace: keshava-project
# spec:
#   selector:
#     app: react-frontend
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: LoadBalancer  # Use NodePort if not on cloud
