apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Or LoadBalancer if you're on cloud
