apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-star-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/disable-validation: "true"  # Bypass webhook validation to prevent failure
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      more_set_headers "X-Content-Type-Options: nosniff";
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"  # Ensures HTTPS redirection doesn't interfere
    nginx.ingress.kubernetes.io/use-regex: "true"  # Enables regex-based routing for better matching
spec:
  ingressClassName: nginx
  rules:
  - host: example.com  # Replace with your actual domain if applicable
    http:
      paths:
      - path: /api/(.*)  # Regex-based path handling
        pathType: ImplementationSpecific
        backend:
          service:
            name: fastapi-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-service
            port:
              number: 80
