apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-star-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: fastapi-service
            port:
              number: 8000
      - path: /  # You may want to specify exact paths here to prevent conflict
        pathType: Prefix
        backend:
          service:
            name: react-service
            port:
              number: 80
