apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Adjusting rewrite rule
    nginx.ingress.kubernetes.io/use-regex: "false"  # Simplify path handling (optional)
spec:
  ingressClassName: nginx
  rules:
  - host: frontend.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  tls:  # Optional: Enable TLS for HTTPS if applicable
  - hosts:
    - frontend.example.com
    secretName: tls-secret-name  # Replace with your TLS secret name
