# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-service
#   namespace: keshava-project
# spec:
#   selector:
#     app: postgres
#   ports:
#     - protocol: TCP
#       port: 5432
#       targetPort: 5432
#   type: NodePort  # Change if needed (NodePort or LoadBalancer)
