apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: cG9ydGZvbGlvX3VzZXI=     # base64 encoded: portfolio_user
  password: c2VjdXJlcGFzc3dvcmQ=     # base64 encoded: securepassword
