---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to Docker group
  user:
    name: "{{ ansible_user }}"
    group: docker
